//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talby.Core.Validation {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talby.Core.Validation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum length cannot be negative..
        /// </summary>
        internal static string IsLengthInRangeMaximumLengthCannotBeNegativeMessage {
            get {
                return ResourceManager.GetString("IsLengthInRangeMaximumLengthCannotBeNegativeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimum length cannot be greater than maximum length..
        /// </summary>
        internal static string IsLengthInRangeMinimumLengthCannotBeGreaterThanMaximumLengthMessage {
            get {
                return ResourceManager.GetString("IsLengthInRangeMinimumLengthCannotBeGreaterThanMaximumLengthMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimum length cannot be negative..
        /// </summary>
        internal static string IsLengthInRangeMinimumLengthCannotBeNegativeMessage {
            get {
                return ResourceManager.GetString("IsLengthInRangeMinimumLengthCannotBeNegativeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0} characters long..
        /// </summary>
        internal static string IsLengthInRangeValueMustBeAtLeastMessageFormat {
            get {
                return ResourceManager.GetString("IsLengthInRangeValueMustBeAtLeastMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must be at most {0} characters long..
        /// </summary>
        internal static string IsLengthInRangeValueMustBeAtMostMessageFormat {
            get {
                return ResourceManager.GetString("IsLengthInRangeValueMustBeAtMostMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must be between {0} and {1} characters long..
        /// </summary>
        internal static string IsLengthInRangeValueMustBeBetweenMessageFormat {
            get {
                return ResourceManager.GetString("IsLengthInRangeValueMustBeBetweenMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is required.
        /// </summary>
        internal static string NotNullValidatorMessage {
            get {
                return ResourceManager.GetString("NotNullValidatorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is required.
        /// </summary>
        internal static string NotEmptyValidatorMessage {
            get {
                return ResourceManager.GetString("NotEmptyValidatorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must be of type {0}..
        /// </summary>
        internal static string IsOfTypeValidatorMessageFormat {
            get {
                return ResourceManager.GetString("IsOfTypeValidatorMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must match the required pattern..
        /// </summary>
        internal static string MatchesRegexMessage {
            get {
                return ResourceManager.GetString("MatchesRegexMessage", resourceCulture);
            }
        }
    }
}
