using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Talby.Core.SourceGenerators;

internal static class DiscriminatedUnionSourceWriter
{
    internal static string GetHintName(INamedTypeSymbol rootSymbol)
    {
        var fullyQualifiedName = rootSymbol.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );
        var sanitizedName = new string(
            fullyQualifiedName
                .Select(static character => char.IsLetterOrDigit(character) ? character : '_')
                .ToArray()
        );

        return $"{sanitizedName}.g.cs";
    }

    internal static string Generate(DiscriminatedUnionRootModel rootModel)
    {
        var builder = new StringBuilder();
        var rootSymbol = rootModel.RootSymbol;

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!rootSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ");
            builder.Append(rootSymbol.ContainingNamespace.ToDisplayString());
            builder.AppendLine(";");
            builder.AppendLine();
        }

        AppendSummary(
            builder,
            0,
            $"Provides generated discriminated-union members for {rootSymbol.Name}."
        );
        AppendIndentedLine(
            builder,
            0,
            $"{GetTypeDeclarationPrefix(rootSymbol)} {rootSymbol.Name}{GetTypeParameterList(rootSymbol)}"
        );
        AppendIndentedLine(builder, 0, "{");

        foreach (var caseModel in rootModel.ValidCases)
        {
            AppendIsProperty(builder, caseModel, 1);
        }

        if (!rootModel.LeafCases.IsDefaultOrEmpty)
        {
            builder.AppendLine();
            AppendMatchResultMethod(builder, rootSymbol, rootModel.LeafCases, 1);

            builder.AppendLine();
            AppendMatchActionMethod(builder, rootSymbol, rootModel.LeafCases, 1);

            foreach (var caseModel in rootModel.LeafCases)
            {
                builder.AppendLine();
                AppendLeafMatchResultMethod(builder, caseModel, 1);
                builder.AppendLine();
                AppendLeafMatchActionMethod(builder, caseModel, 1);
            }
        }

        AppendIndentedLine(builder, 0, "}");

        return builder.ToString();
    }

    private static void AppendIsProperty(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(builder, indentLevel, $"Gets whether this instance is a {caseName}.");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public bool Is{caseName} => this is {GetTypeReference(caseModel.Symbol)};"
        );
    }

    private static void AppendMatchResultMethod(
        StringBuilder builder,
        INamedTypeSymbol rootSymbol,
        ImmutableArray<DiscriminatedUnionCaseModel> leafCases,
        int indentLevel
    )
    {
        AppendSummary(
            builder,
            indentLevel,
            $"Matches this instance against the {GetCaseNameList(leafCases)} cases."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <typeparam name=\"TResult\">The result type.</typeparam>"
        );

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"/// <param name=\"match{caseModel.Symbol.Name}Func\">The function invoked for {caseModel.Symbol.Name}.</param>"
            );
        }

        AppendIndentedLine(builder, indentLevel, "/// <returns>The matched result.</returns>");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <exception cref=\"global::System.InvalidOperationException\">Thrown when the runtime type is not one of the generated {rootSymbol.Name} cases.</exception>"
        );
        AppendIndentedLine(builder, indentLevel, "public TResult Match<TResult>(");

        for (var index = 0; index < leafCases.Length; index++)
        {
            var caseModel = leafCases[index];
            var separator = index == leafCases.Length - 1 ? string.Empty : ",";

            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"global::System.Func<{GetTypeReference(caseModel.Symbol)}, TResult> match{caseModel.Symbol.Name}Func{separator}"
            );
        }

        AppendIndentedLine(builder, indentLevel, ")");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(builder, indentLevel + 1, "return this switch");
        AppendIndentedLine(builder, indentLevel + 1, "{");

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"{GetTypeReference(caseModel.Symbol)} caseValue => match{caseModel.Symbol.Name}Func(caseValue),"
            );
        }

        AppendIndentedLine(
            builder,
            indentLevel + 2,
            $"_ => throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\"),"
        );
        AppendIndentedLine(builder, indentLevel + 1, "};");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendMatchActionMethod(
        StringBuilder builder,
        INamedTypeSymbol rootSymbol,
        ImmutableArray<DiscriminatedUnionCaseModel> leafCases,
        int indentLevel
    )
    {
        AppendSummary(
            builder,
            indentLevel,
            $"Invokes the matching action for the {GetCaseNameList(leafCases)} cases."
        );

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"/// <param name=\"match{caseModel.Symbol.Name}Action\">The action invoked for {caseModel.Symbol.Name}.</param>"
            );
        }

        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <exception cref=\"global::System.InvalidOperationException\">Thrown when the runtime type is not one of the generated {rootSymbol.Name} cases.</exception>"
        );
        AppendIndentedLine(builder, indentLevel, "public void Match(");

        for (var index = 0; index < leafCases.Length; index++)
        {
            var caseModel = leafCases[index];
            var separator = index == leafCases.Length - 1 ? string.Empty : ",";

            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"global::System.Action<{GetTypeReference(caseModel.Symbol)}> match{caseModel.Symbol.Name}Action{separator}"
            );
        }

        AppendIndentedLine(builder, indentLevel, ")");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(builder, indentLevel + 1, "switch (this)");
        AppendIndentedLine(builder, indentLevel + 1, "{");

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"case {GetTypeReference(caseModel.Symbol)} caseValue:"
            );
            AppendIndentedLine(
                builder,
                indentLevel + 3,
                $"match{caseModel.Symbol.Name}Action(caseValue);"
            );
            AppendIndentedLine(builder, indentLevel + 3, "break;");
        }

        AppendIndentedLine(builder, indentLevel + 2, "default:");
        AppendIndentedLine(
            builder,
            indentLevel + 3,
            $"throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\");"
        );
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendLeafMatchResultMethod(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(
            builder,
            indentLevel,
            $"Returns the supplied default value unless this instance is a {caseName}."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <typeparam name=\"TResult\">The result type.</typeparam>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <param name=\"defaultValue\">The value returned when the instance does not match.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <param name=\"matchFunc\">The function invoked when this instance is a {caseName}.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <returns>The matched result or the default value.</returns>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public TResult Match{caseName}<TResult>(TResult defaultValue, global::System.Func<{GetTypeReference(caseModel.Symbol)}, TResult> matchFunc)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"return this is {GetTypeReference(caseModel.Symbol)} caseValue ? matchFunc(caseValue) : defaultValue;"
        );
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendLeafMatchActionMethod(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(
            builder,
            indentLevel,
            $"Invokes the supplied action when this instance is a {caseName}."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <param name=\"matchAction\">The action invoked when this instance is a {caseName}.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <param name=\"defaultAction\">The action invoked when the instance does not match. If null, nothing happens.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public void Match{caseName}(global::System.Action<{GetTypeReference(caseModel.Symbol)}> matchAction, global::System.Action? defaultAction = null)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"if (this is {GetTypeReference(caseModel.Symbol)} caseValue)"
        );
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(builder, indentLevel + 2, "matchAction(caseValue);");
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel + 1, "else");
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(builder, indentLevel + 2, "if (defaultAction is not null)");
        AppendIndentedLine(builder, indentLevel + 2, "{");
        AppendIndentedLine(builder, indentLevel + 3, "defaultAction();");
        AppendIndentedLine(builder, indentLevel + 2, "}");
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static string GetCaseNameList(ImmutableArray<DiscriminatedUnionCaseModel> cases)
    {
        return string.Join(", ", cases.Select(static caseModel => caseModel.Symbol.Name));
    }

    private static string GetTypeDeclarationPrefix(INamedTypeSymbol symbol)
    {
        if (symbol.IsRecord)
        {
            return symbol.TypeKind == TypeKind.Struct ? "partial record struct" : "partial record";
        }

        return symbol.TypeKind == TypeKind.Struct ? "partial struct" : "partial class";
    }

    private static string GetTypeReference(INamedTypeSymbol symbol)
    {
        return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string GetTypeParameterList(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
        {
            return string.Empty;
        }

        return $"<{string.Join(", ", symbol.TypeParameters.Select(static typeParameter => typeParameter.Name))}>";
    }

    private static void AppendSummary(StringBuilder builder, int indentLevel, string summary)
    {
        AppendIndentedLine(builder, indentLevel, "/// <summary>");
        AppendIndentedLine(builder, indentLevel, $"/// {summary}");
        AppendIndentedLine(builder, indentLevel, "/// </summary>");
    }

    private static void AppendIndentedLine(StringBuilder builder, int indentLevel, string text)
    {
        builder.Append(new string(' ', indentLevel * 4));
        builder.AppendLine(text);
    }
}
