using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Talby.Core.SourceGenerators;

internal static class DiscriminatedUnionSourceWriter
{
    internal static string GetHintName(INamedTypeSymbol rootSymbol)
    {
        var fullyQualifiedName = rootSymbol.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );
        var sanitizedName = new string(
            fullyQualifiedName
                .Select(static character => char.IsLetterOrDigit(character) ? character : '_')
                .ToArray()
        );

        return $"{sanitizedName}.g.cs";
    }

    internal static string Generate(DiscriminatedUnionRootModel rootModel)
    {
        var builder = new StringBuilder();
        var rootSymbol = rootModel.RootSymbol;
        var matchCases = GetMatchCases(rootModel);
        var topLevelCases = GetTopLevelCases(rootModel);

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!rootSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ");
            builder.Append(rootSymbol.ContainingNamespace.ToDisplayString());
            builder.AppendLine(";");
            builder.AppendLine();
        }

        AppendSummary(
            builder,
            0,
            $"Provides generated discriminated-union members for {rootSymbol.Name}."
        );
        AppendIndentedLine(
            builder,
            0,
            $"{GetTypeDeclarationPrefix(rootSymbol)} {rootSymbol.Name}{GetTypeParameterList(rootSymbol)}"
        );
        AppendIndentedLine(builder, 0, "{");

        foreach (var caseModel in rootModel.ValidCases)
        {
            AppendIsProperty(builder, caseModel, 1);
        }

        if (!matchCases.IsDefaultOrEmpty)
        {
            builder.AppendLine();
            AppendBranchAwareMatchResultMethod(
                builder,
                rootSymbol,
                rootModel,
                matchCases,
                topLevelCases,
                1
            );

            builder.AppendLine();
            AppendBranchAwareMatchActionMethod(
                builder,
                rootSymbol,
                rootModel,
                matchCases,
                topLevelCases,
                1
            );

            foreach (var caseModel in rootModel.LeafCases)
            {
                builder.AppendLine();
                AppendBranchAwareLeafMatchResultMethod(builder, caseModel, 1);
                builder.AppendLine();
                AppendBranchAwareLeafMatchActionMethod(builder, caseModel, 1);
            }
        }

        AppendIndentedLine(builder, 0, "}");

        return builder.ToString();
    }

    private static void AppendIsProperty(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(builder, indentLevel, $"Gets whether this instance is a {caseName}.");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public bool Is{caseName} => this is {GetTypeReference(caseModel.Symbol)};"
        );
    }

    private static void AppendMatchResultMethod(
        StringBuilder builder,
        INamedTypeSymbol rootSymbol,
        ImmutableArray<DiscriminatedUnionCaseModel> leafCases,
        int indentLevel
    )
    {
        AppendSummary(
            builder,
            indentLevel,
            $"Matches this instance against the {GetCaseNameList(leafCases)} cases."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <typeparam name=\"TResult\">The result type.</typeparam>"
        );

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"/// <param name=\"match{caseModel.Symbol.Name}Func\">The function invoked for {caseModel.Symbol.Name}.</param>"
            );
        }

        AppendIndentedLine(builder, indentLevel, "/// <returns>The matched result.</returns>");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <exception cref=\"global::System.InvalidOperationException\">Thrown when the runtime type is not one of the generated {rootSymbol.Name} cases.</exception>"
        );
        AppendIndentedLine(builder, indentLevel, "public TResult Match<TResult>(");

        for (var index = 0; index < leafCases.Length; index++)
        {
            var caseModel = leafCases[index];
            var separator = index == leafCases.Length - 1 ? string.Empty : ",";

            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"global::System.Func<{GetTypeReference(caseModel.Symbol)}, TResult> match{caseModel.Symbol.Name}Func{separator}"
            );
        }

        AppendIndentedLine(builder, indentLevel, ")");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(builder, indentLevel + 1, "return this switch");
        AppendIndentedLine(builder, indentLevel + 1, "{");

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"{GetTypeReference(caseModel.Symbol)} caseValue => match{caseModel.Symbol.Name}Func(caseValue),"
            );
        }

        AppendIndentedLine(
            builder,
            indentLevel + 2,
            $"_ => throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\"),"
        );
        AppendIndentedLine(builder, indentLevel + 1, "};");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendMatchActionMethod(
        StringBuilder builder,
        INamedTypeSymbol rootSymbol,
        ImmutableArray<DiscriminatedUnionCaseModel> leafCases,
        int indentLevel
    )
    {
        AppendSummary(
            builder,
            indentLevel,
            $"Invokes the matching action for the {GetCaseNameList(leafCases)} cases."
        );

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"/// <param name=\"match{caseModel.Symbol.Name}Action\">The action invoked for {caseModel.Symbol.Name}.</param>"
            );
        }

        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <exception cref=\"global::System.InvalidOperationException\">Thrown when the runtime type is not one of the generated {rootSymbol.Name} cases.</exception>"
        );
        AppendIndentedLine(builder, indentLevel, "public void Match(");

        for (var index = 0; index < leafCases.Length; index++)
        {
            var caseModel = leafCases[index];
            var separator = index == leafCases.Length - 1 ? string.Empty : ",";

            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"global::System.Action<{GetTypeReference(caseModel.Symbol)}> match{caseModel.Symbol.Name}Action{separator}"
            );
        }

        AppendIndentedLine(builder, indentLevel, ")");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(builder, indentLevel + 1, "switch (this)");
        AppendIndentedLine(builder, indentLevel + 1, "{");

        foreach (var caseModel in leafCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"case {GetTypeReference(caseModel.Symbol)} caseValue:"
            );
            AppendIndentedLine(
                builder,
                indentLevel + 3,
                $"match{caseModel.Symbol.Name}Action(caseValue);"
            );
            AppendIndentedLine(builder, indentLevel + 3, "break;");
        }

        AppendIndentedLine(builder, indentLevel + 2, "default:");
        AppendIndentedLine(
            builder,
            indentLevel + 3,
            $"throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\");"
        );
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendBranchAwareMatchResultMethod(
        StringBuilder builder,
        INamedTypeSymbol rootSymbol,
        DiscriminatedUnionRootModel rootModel,
        ImmutableArray<DiscriminatedUnionCaseModel> matchCases,
        ImmutableArray<DiscriminatedUnionCaseModel> topLevelCases,
        int indentLevel
    )
    {
        AppendSummary(
            builder,
            indentLevel,
            $"Matches this instance against the {GetCaseNameList(matchCases)} cases."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <typeparam name=\"TResult\">The result type.</typeparam>"
        );

        foreach (var caseModel in matchCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"/// <param name=\"{GetMatchParameterName(caseModel)}\">The function invoked for {caseModel.Symbol.Name}.</param>"
            );
        }

        AppendIndentedLine(builder, indentLevel, "/// <returns>The matched result.</returns>");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <exception cref=\"global::System.InvalidOperationException\">Thrown when the runtime type is not one of the generated {rootSymbol.Name} cases.</exception>"
        );
        AppendIndentedLine(builder, indentLevel, "public TResult Match<TResult>(");

        for (var index = 0; index < matchCases.Length; index++)
        {
            var caseModel = matchCases[index];
            var separator = index == matchCases.Length - 1 ? string.Empty : ",";
            var optionalSuffix = IsOptionalMatchCase(rootModel, caseModel) ? "?" : string.Empty;
            var defaultValue = IsOptionalMatchCase(rootModel, caseModel) ? " = null" : string.Empty;

            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"global::System.Func<{GetTypeReference(caseModel.Symbol)}, TResult>{optionalSuffix} {GetMatchParameterName(caseModel)}{defaultValue}{separator}"
            );
        }

        AppendIndentedLine(builder, indentLevel, ")");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendBranchAwareMatchValidationFunctions(builder, rootModel, topLevelCases, indentLevel + 1);

        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"if (!({GetValidationInvocation(topLevelCases)}))"
        );
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 2,
            $"throw new global::System.InvalidOperationException(\"Invalid {rootSymbol.Name} Match handler combination.\");"
        );
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel + 1, "switch (this)");
        AppendIndentedLine(builder, indentLevel + 1, "{");

        foreach (var caseModel in matchCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"case {GetTypeReference(caseModel.Symbol)} caseValue:"
            );
            AppendIndentedLine(builder, indentLevel + 2, "{");
            AppendBranchAwareMatchResultDispatch(
                builder,
                rootModel,
                rootSymbol,
                caseModel,
                indentLevel + 3
            );
            AppendIndentedLine(builder, indentLevel + 2, "}");
        }

        AppendIndentedLine(builder, indentLevel + 2, "default:");
        AppendIndentedLine(
            builder,
            indentLevel + 3,
            $"throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\");"
        );
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendBranchAwareMatchActionMethod(
        StringBuilder builder,
        INamedTypeSymbol rootSymbol,
        DiscriminatedUnionRootModel rootModel,
        ImmutableArray<DiscriminatedUnionCaseModel> matchCases,
        ImmutableArray<DiscriminatedUnionCaseModel> topLevelCases,
        int indentLevel
    )
    {
        AppendSummary(
            builder,
            indentLevel,
            $"Invokes the matching action for the {GetCaseNameList(matchCases)} cases."
        );

        foreach (var caseModel in matchCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"/// <param name=\"{GetMatchParameterName(caseModel)}\">The action invoked for {caseModel.Symbol.Name}.</param>"
            );
        }

        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <exception cref=\"global::System.InvalidOperationException\">Thrown when the runtime type is not one of the generated {rootSymbol.Name} cases.</exception>"
        );
        AppendIndentedLine(builder, indentLevel, "public void Match(");

        for (var index = 0; index < matchCases.Length; index++)
        {
            var caseModel = matchCases[index];
            var separator = index == matchCases.Length - 1 ? string.Empty : ",";
            var optionalSuffix = IsOptionalMatchCase(rootModel, caseModel) ? "?" : string.Empty;
            var defaultValue = IsOptionalMatchCase(rootModel, caseModel) ? " = null" : string.Empty;

            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"global::System.Action<{GetTypeReference(caseModel.Symbol)}>{optionalSuffix} {GetMatchParameterName(caseModel)}{defaultValue}{separator}"
            );
        }

        AppendIndentedLine(builder, indentLevel, ")");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendBranchAwareMatchValidationFunctions(builder, rootModel, topLevelCases, indentLevel + 1);

        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"if (!({GetValidationInvocation(topLevelCases)}))"
        );
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 2,
            $"throw new global::System.InvalidOperationException(\"Invalid {rootSymbol.Name} Match handler combination.\");"
        );
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel + 1, "switch (this)");
        AppendIndentedLine(builder, indentLevel + 1, "{");

        foreach (var caseModel in matchCases)
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"case {GetTypeReference(caseModel.Symbol)} caseValue:"
            );
            AppendIndentedLine(builder, indentLevel + 2, "{");
            AppendBranchAwareMatchActionDispatch(
                builder,
                rootModel,
                rootSymbol,
                caseModel,
                indentLevel + 3
            );
            AppendIndentedLine(builder, indentLevel + 2, "}");
        }

        AppendIndentedLine(builder, indentLevel + 2, "default:");
        AppendIndentedLine(
            builder,
            indentLevel + 3,
            $"throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\");"
        );
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendBranchAwareMatchValidationFunctions(
        StringBuilder builder,
        DiscriminatedUnionRootModel rootModel,
        ImmutableArray<DiscriminatedUnionCaseModel> topLevelCases,
        int indentLevel
    )
    {
        var isFirst = true;

        foreach (var topLevelCase in topLevelCases)
        {
            if (!isFirst)
            {
                builder.AppendLine();
            }

            AppendBranchAwareMatchValidationFunction(builder, rootModel, topLevelCase, indentLevel);
            isFirst = false;
        }
    }

    private static void AppendBranchAwareMatchValidationFunction(
        StringBuilder builder,
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;
        var descendantCases = GetDescendantCases(rootModel, caseModel);
        var directChildren = GetDirectChildren(rootModel, caseModel);

        AppendIndentedLine(builder, indentLevel, $"bool Validate{caseName}()");
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"if ({GetMatchParameterName(caseModel)} is not null)"
        );
        AppendIndentedLine(builder, indentLevel + 1, "{");

        if (descendantCases.IsEmpty)
        {
            AppendIndentedLine(builder, indentLevel + 2, "return true;");
        }
        else
        {
            AppendIndentedLine(
                builder,
                indentLevel + 2,
                $"return {string.Join(" && ", descendantCases.Select(static descendantCase => $"{GetMatchParameterName(descendantCase)} is null"))};"
            );
        }

        AppendIndentedLine(builder, indentLevel + 1, "}");

        if (directChildren.IsEmpty)
        {
            AppendIndentedLine(builder, indentLevel + 1, "return false;");
        }
        else
        {
            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"return {string.Join(" && ", directChildren.Select(static childCase => $"Validate{childCase.Symbol.Name}()"))};"
            );
        }

        AppendIndentedLine(builder, indentLevel, "}");

        foreach (var childCase in directChildren)
        {
            builder.AppendLine();
            AppendBranchAwareMatchValidationFunction(builder, rootModel, childCase, indentLevel);
        }
    }

    private static void AppendBranchAwareMatchResultDispatch(
        StringBuilder builder,
        DiscriminatedUnionRootModel rootModel,
        INamedTypeSymbol rootSymbol,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        foreach (var ancestorCase in GetGroupingAncestors(rootModel, caseModel))
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"if ({GetMatchParameterName(ancestorCase)} is not null)"
            );
            AppendIndentedLine(builder, indentLevel, "{");
            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"return {GetMatchParameterName(ancestorCase)}(caseValue);"
            );
            AppendIndentedLine(builder, indentLevel, "}");
        }

        AppendIndentedLine(
            builder,
            indentLevel,
            $"if ({GetMatchParameterName(caseModel)} is not null)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"return {GetMatchParameterName(caseModel)}(caseValue);"
        );
        AppendIndentedLine(builder, indentLevel, "}");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\");"
        );
    }

    private static void AppendBranchAwareMatchActionDispatch(
        StringBuilder builder,
        DiscriminatedUnionRootModel rootModel,
        INamedTypeSymbol rootSymbol,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        foreach (var ancestorCase in GetGroupingAncestors(rootModel, caseModel))
        {
            AppendIndentedLine(
                builder,
                indentLevel,
                $"if ({GetMatchParameterName(ancestorCase)} is not null)"
            );
            AppendIndentedLine(builder, indentLevel, "{");
            AppendIndentedLine(
                builder,
                indentLevel + 1,
                $"{GetMatchParameterName(ancestorCase)}(caseValue);"
            );
            AppendIndentedLine(builder, indentLevel + 1, "return;");
            AppendIndentedLine(builder, indentLevel, "}");
        }

        AppendIndentedLine(
            builder,
            indentLevel,
            $"if ({GetMatchParameterName(caseModel)} is not null)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"{GetMatchParameterName(caseModel)}(caseValue);"
        );
        AppendIndentedLine(builder, indentLevel + 1, "return;");
        AppendIndentedLine(builder, indentLevel, "}");
        AppendIndentedLine(
            builder,
            indentLevel,
            $"throw new global::System.InvalidOperationException(\"Unknown {rootSymbol.Name} type.\");"
        );
    }

    private static void AppendBranchAwareLeafMatchResultMethod(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(
            builder,
            indentLevel,
            $"Returns the supplied default value unless this instance is a {caseName}."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <typeparam name=\"TResult\">The result type.</typeparam>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <param name=\"defaultValue\">The value returned when the instance does not match.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <param name=\"onMatch\">The function invoked when this instance is a {caseName}.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <returns>The matched result or the default value.</returns>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public TResult Match{caseName}<TResult>(TResult defaultValue, global::System.Func<{GetTypeReference(caseModel.Symbol)}, TResult> onMatch)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"return this is {GetTypeReference(caseModel.Symbol)} caseValue ? onMatch(caseValue) : defaultValue;"
        );
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendBranchAwareLeafMatchActionMethod(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(
            builder,
            indentLevel,
            $"Invokes the supplied action when this instance is a {caseName}."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <param name=\"onAction\">The action invoked when this instance is a {caseName}.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <param name=\"defaultAction\">The action invoked when the instance does not match. If null, nothing happens.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public void Match{caseName}(global::System.Action<{GetTypeReference(caseModel.Symbol)}> onAction, global::System.Action? defaultAction = null)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"if (this is {GetTypeReference(caseModel.Symbol)} caseValue)"
        );
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(builder, indentLevel + 2, "onAction(caseValue);");
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel + 1, "else");
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(builder, indentLevel + 2, "if (defaultAction is not null)");
        AppendIndentedLine(builder, indentLevel + 2, "{");
        AppendIndentedLine(builder, indentLevel + 3, "defaultAction();");
        AppendIndentedLine(builder, indentLevel + 2, "}");
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static ImmutableArray<DiscriminatedUnionCaseModel> GetMatchCases(
        DiscriminatedUnionRootModel rootModel
    )
    {
        if (rootModel.ValidCases.IsDefaultOrEmpty)
        {
            return ImmutableArray<DiscriminatedUnionCaseModel>.Empty;
        }

        var matchCases = ImmutableArray.CreateBuilder<DiscriminatedUnionCaseModel>();
        matchCases.AddRange(rootModel.LeafCases);
        matchCases.AddRange(rootModel.GroupingCases);

        return matchCases.ToImmutable();
    }

    private static ImmutableArray<DiscriminatedUnionCaseModel> GetTopLevelCases(
        DiscriminatedUnionRootModel rootModel
    )
    {
        if (rootModel.ValidCases.IsDefaultOrEmpty)
        {
            return ImmutableArray<DiscriminatedUnionCaseModel>.Empty;
        }

        var topLevelCases = ImmutableArray.CreateBuilder<DiscriminatedUnionCaseModel>();

        foreach (var caseModel in rootModel.ValidCases)
        {
            if (GetParentCase(rootModel, caseModel) is null)
            {
                topLevelCases.Add(caseModel);
            }
        }

        return topLevelCases.ToImmutable();
    }

    private static ImmutableArray<DiscriminatedUnionCaseModel> GetGroupingAncestors(
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel
    )
    {
        if (rootModel.ValidCases.IsDefaultOrEmpty)
        {
            return ImmutableArray<DiscriminatedUnionCaseModel>.Empty;
        }

        var groupingAncestors = ImmutableArray.CreateBuilder<DiscriminatedUnionCaseModel>();

        for (
            var currentParent = GetParentCase(rootModel, caseModel);
            currentParent is not null;
            currentParent = GetParentCase(rootModel, currentParent)
        )
        {
            if (IsGroupingCase(rootModel, currentParent))
            {
                groupingAncestors.Add(currentParent);
            }
        }

        return groupingAncestors.ToImmutable();
    }

    private static ImmutableArray<DiscriminatedUnionCaseModel> GetDirectChildren(
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel
    )
    {
        if (rootModel.ValidCases.IsDefaultOrEmpty)
        {
            return ImmutableArray<DiscriminatedUnionCaseModel>.Empty;
        }

        var directChildren = ImmutableArray.CreateBuilder<DiscriminatedUnionCaseModel>();

        foreach (var candidateCase in rootModel.ValidCases)
        {
            if (SymbolEqualityComparer.Default.Equals(candidateCase.Symbol, caseModel.Symbol))
            {
                continue;
            }

            var parentCase = GetParentCase(rootModel, candidateCase);

            if (
                parentCase is not null
                && SymbolEqualityComparer.Default.Equals(
                    parentCase.Symbol.OriginalDefinition,
                    caseModel.Symbol.OriginalDefinition
                )
            )
            {
                directChildren.Add(candidateCase);
            }
        }

        return directChildren.ToImmutable();
    }

    private static ImmutableArray<DiscriminatedUnionCaseModel> GetDescendantCases(
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel
    )
    {
        var descendantCases = ImmutableArray.CreateBuilder<DiscriminatedUnionCaseModel>();

        foreach (var childCase in GetDirectChildren(rootModel, caseModel))
        {
            descendantCases.Add(childCase);
            descendantCases.AddRange(GetDescendantCases(rootModel, childCase));
        }

        return descendantCases.ToImmutable();
    }

    private static DiscriminatedUnionCaseModel? GetParentCase(
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel
    )
    {
        for (
            var currentBaseType = caseModel.Symbol.BaseType;
            currentBaseType is not null;
            currentBaseType = currentBaseType.BaseType
        )
        {
            var parentCase = rootModel.ValidCases.FirstOrDefault(candidateCase =>
                SymbolEqualityComparer.Default.Equals(
                    candidateCase.Symbol.OriginalDefinition,
                    currentBaseType.OriginalDefinition
                )
            );

            if (parentCase is not null)
            {
                return parentCase;
            }
        }

        return null;
    }

    private static bool IsGroupingCase(
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel
    )
    {
        return rootModel.GroupingCases.Any(groupingCase =>
            SymbolEqualityComparer.Default.Equals(
                groupingCase.Symbol.OriginalDefinition,
                caseModel.Symbol.OriginalDefinition
            )
        );
    }

    private static bool IsOptionalMatchCase(
        DiscriminatedUnionRootModel rootModel,
        DiscriminatedUnionCaseModel caseModel
    )
    {
        return GetGroupingAncestors(rootModel, caseModel).Length > 0 || IsGroupingCase(rootModel, caseModel);
    }

    private static string GetMatchParameterName(DiscriminatedUnionCaseModel caseModel)
    {
        return $"on{caseModel.Symbol.Name}";
    }

    private static string GetValidationInvocation(
        ImmutableArray<DiscriminatedUnionCaseModel> topLevelCases
    )
    {
        return string.Join(
            " && ",
            topLevelCases.Select(static caseModel => $"Validate{caseModel.Symbol.Name}()")
        );
    }

    private static void AppendLeafMatchResultMethod(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(
            builder,
            indentLevel,
            $"Returns the supplied default value unless this instance is a {caseName}."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <typeparam name=\"TResult\">The result type.</typeparam>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <param name=\"defaultValue\">The value returned when the instance does not match.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <param name=\"matchFunc\">The function invoked when this instance is a {caseName}.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <returns>The matched result or the default value.</returns>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public TResult Match{caseName}<TResult>(TResult defaultValue, global::System.Func<{GetTypeReference(caseModel.Symbol)}, TResult> matchFunc)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"return this is {GetTypeReference(caseModel.Symbol)} caseValue ? matchFunc(caseValue) : defaultValue;"
        );
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static void AppendLeafMatchActionMethod(
        StringBuilder builder,
        DiscriminatedUnionCaseModel caseModel,
        int indentLevel
    )
    {
        var caseName = caseModel.Symbol.Name;

        AppendSummary(
            builder,
            indentLevel,
            $"Invokes the supplied action when this instance is a {caseName}."
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"/// <param name=\"matchAction\">The action invoked when this instance is a {caseName}.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            "/// <param name=\"defaultAction\">The action invoked when the instance does not match. If null, nothing happens.</param>"
        );
        AppendIndentedLine(
            builder,
            indentLevel,
            $"public void Match{caseName}(global::System.Action<{GetTypeReference(caseModel.Symbol)}> matchAction, global::System.Action? defaultAction = null)"
        );
        AppendIndentedLine(builder, indentLevel, "{");
        AppendIndentedLine(
            builder,
            indentLevel + 1,
            $"if (this is {GetTypeReference(caseModel.Symbol)} caseValue)"
        );
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(builder, indentLevel + 2, "matchAction(caseValue);");
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel + 1, "else");
        AppendIndentedLine(builder, indentLevel + 1, "{");
        AppendIndentedLine(builder, indentLevel + 2, "if (defaultAction is not null)");
        AppendIndentedLine(builder, indentLevel + 2, "{");
        AppendIndentedLine(builder, indentLevel + 3, "defaultAction();");
        AppendIndentedLine(builder, indentLevel + 2, "}");
        AppendIndentedLine(builder, indentLevel + 1, "}");
        AppendIndentedLine(builder, indentLevel, "}");
    }

    private static string GetCaseNameList(ImmutableArray<DiscriminatedUnionCaseModel> cases)
    {
        return string.Join(", ", cases.Select(static caseModel => caseModel.Symbol.Name));
    }

    private static string GetTypeDeclarationPrefix(INamedTypeSymbol symbol)
    {
        if (symbol.IsRecord)
        {
            return symbol.TypeKind == TypeKind.Struct ? "partial record struct" : "partial record";
        }

        return symbol.TypeKind == TypeKind.Struct ? "partial struct" : "partial class";
    }

    private static string GetTypeReference(INamedTypeSymbol symbol)
    {
        return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string GetTypeParameterList(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
        {
            return string.Empty;
        }

        return $"<{string.Join(", ", symbol.TypeParameters.Select(static typeParameter => typeParameter.Name))}>";
    }

    private static void AppendSummary(StringBuilder builder, int indentLevel, string summary)
    {
        AppendIndentedLine(builder, indentLevel, "/// <summary>");
        AppendIndentedLine(builder, indentLevel, $"/// {summary}");
        AppendIndentedLine(builder, indentLevel, "/// </summary>");
    }

    private static void AppendIndentedLine(StringBuilder builder, int indentLevel, string text)
    {
        builder.Append(new string(' ', indentLevel * 4));
        builder.AppendLine(text);
    }
}
