namespace Talby.Core.SourceGenerators;

internal static class GenerateDiscriminatedUnionAttribute
{
    internal const string HintName = "GenerateDiscriminatedUnionAttribute.g.cs";

    internal const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace Talby.Core.SourceGenerators;

        [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
        internal sealed class GenerateDiscriminatedUnionAttribute : System.Attribute
        {
        }
        """;
}
